/**
* @File Name : userDataCardClass.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 3, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 3, 2024 |   | Initial Version
**/

public class userDataCardClass {
	@AuraEnabled
	Public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}